#!/bin/sh

if [ -z "${ANSIBLE_HOME}" ]
then
    echo "ANSIBLE_HOME is undefined. Go into ansible directory and run 'source hacking/env-setup'"
    exit 1
fi

cp ${ANSIBLE_HOME}/test/units/modules/network/m4300/*.py test/units/modules/network/m4300/
cp ${ANSIBLE_HOME}/test/units/modules/network/m4300/fixtures/* test/units/modules/network/m4300/fixtures/
cp ${ANSIBLE_HOME}/lib/ansible/module_utils/network/m4300/*.py module_utils/network/m4300/
cp ${ANSIBLE_HOME}/lib/ansible/modules/network/m4300/*.py library/
cp ${ANSIBLE_HOME}/lib/ansible/plugins/cliconf/m4300.py plugins/cliconf/m4300.py
cp ${ANSIBLE_HOME}/lib/ansible/plugins/terminal/m4300.py plugins/terminal/m4300.py
